import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { apiKey, systemPrompt, userPrompt } = body;

    if (!apiKey || typeof apiKey !== 'string') {
      return NextResponse.json({ error: 'Gemini API key is required' }, { status: 400 });
    }

    if (!userPrompt || typeof userPrompt !== 'string') {
      return NextResponse.json({ error: 'User prompt is required' }, { status: 400 });
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;

    const geminiBody: Record<string, unknown> = {
      contents: [
        {
          role: 'user',
          parts: [{ text: userPrompt }],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        topP: 0.95,
        topK: 40,
        maxOutputTokens: 4096,
      },
    };

    if (systemPrompt) {
      geminiBody.systemInstruction = {
        parts: [{ text: systemPrompt }],
      };
    }

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(geminiBody),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage = (errorData as Record<string, unknown>)?.error
        ? ((errorData as Record<string, unknown>).error as Record<string, unknown>)?.message || 'Gemini API error'
        : `Gemini API returned ${response.status}`;
      return NextResponse.json(
        { error: typeof errorMessage === 'string' ? errorMessage : 'Gemini API error' },
        { status: response.status }
      );
    }

    const data = await response.json();
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      return NextResponse.json(
        { error: 'No response generated by Gemini' },
        { status: 500 }
      );
    }

    return NextResponse.json({ response: text });
  } catch (error) {
    console.error('Gemini API error:', error);
    return NextResponse.json(
      { error: 'Failed to call Gemini API. Check your API key and try again.' },
      { status: 500 }
    );
  }
}
